version: "3.9"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    expose:
      - "5432"

  frontend:
    build: ./frontend
    volumes:
      - ./storage:/storage:ro
    ports:
      - "80:80"

  backend:
    build: ./rust_backend
    environment:
      RUST_LOG: "info"
      DATABASE_URL: "postgresql://user:password@database:5432/postgres"
      COOKIE_KEY: "5QBj3KjxcD7pgI8r5QBj3KjxcD7pgI8r5QBj3KjxcD7pgI8r5QBj3KjxcD7pgI8r"
      PASSWORD_HASH_SALT: "fhasdkjkfjdjnfaosdhj"
      ADDRESS: "0.0.0.0:8080"
      STORAGE_PATH: "/storage"
    volumes:
      - ./storage:/storage
    expose:
      - "8080"
    restart: on-failure
    depends_on:
      - database
